config/routes.rb
Rails.application.routes.draw do
  get '/sobre' => 'pages#about'
  get '/termos-de-uso' => 'pages#terms', as: 'termos'
  get '/batata-precisa-de-voce' => 'pages#batata-precisa-de-voce'
  get '/baixo-centro' => 'pages#baixo-centro'
  get '/boa-praca' => 'pages#boa-praca'

  get '/search', to: 'home#search'
  get '/auth/:provider/callback' => 'omniauth#create'

  resources :users,
    :controller => 'users',
    :only => [:new, :create, :destroy]

  root to: 'home#index'

  localized do
    resources :interventions, only: [:index]
    resources :collectives, only: [:create, :index, :show, :edit, :update, :new] do
      resources :interventions, module: 'collectives'
    end
  end
end

app/views/shared/_flash.html.erb
<div id="flash">
  <div class="wrapper">
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="wrapper">
    <h6 class="logo logo--small"><%= link_to title, root_path %></h6>

    <div class="footer--left">
      <nav class="footer__menu">
        <%= link_to 'Sobre', sobre_path, class: 'footer__menu__link' %>
        <%= link_to 'Termos de serviço', termos_path, class: 'footer__menu__link' %>
      </nav>

      <div class="footer__facebook">
        <div class="fb-like" data-href="https://www.facebook.com/fis10inspira" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
      </div>
    </div>

    <div class="footer--right">
      <nav class="footer__menu">
        <%= link_to 'Open Source', 'https://github.com/tracersoft/inspirasp', class: 'footer__menu__link github', target: '_blank' %>

        <span class="footer__menu__span--margin">
          <span class="footer__menu__span">Made with</span>
          <span class="footer__menu__span icon-heart"></span>
          <span class="footer__menu__span">by</span>
        </span>

        <%= link_to 'tracersoft', 'http://tracersoft.com.br/', class: 'footer__menu__link tracer', target: '_blank' %>
      </nav>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <div class="wrapper">
    <h1 class="logo logo--header logo--normal"><%= link_to title, root_path %></h1>

    <nav class="menu-navigation">
      <div class="menu menu--left">
        <ul class="menu__list">
          <li class="menu__item">
            <%= link_to 'Sobre',
                sobre_path,
                class: 'menu__link' %>
          </li>

          <li class="menu__item">
            <%= link_to I18n.t("menu.explorer"),
                interventions_path,
                class: 'menu__link' %>
          </li>
        </ul>
      </div>

      <div class="menu menu--right">
        <% if signed_in? %>
          <ul class="menu__list">
            <li class="menu__item">
              <%= render partial: '/shared/user_menu' %>
            </li>
          </ul>
        <% else %>
          <ul class="menu__list">
            <li class="menu__item">
              <label class="menu__link" for="session_email">Entrar</label>

              <div class="login-box login-box--center">
                <%= render partial: '/sessions/form_header' %>
              </div>
            </li>

            <li class="menu__item">
              <%= link_to 'Cadastrar minha praça',
                          sign_up_path,
                          class: 'menu__link menu__link--red' %>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>

    <a class="menu-button-nav" id="nav-close-btn" href="#" data-menu-mobile>Return to Content</a>
  </div>
</header>

app/views/shared/_user_menu.html.erb
<%= link_to 'javascript:;', class: 'menu__link menu-user' do %>
  <figure class="menu-user__image"
    data-cover="<%= current_collective && attachment_url(current_collective, :avatar, :fill, 100, 100) %>">
  </figure>
  <div class="menu-user__user"><%= current_user.email %></div>
<% end -%>

<div class="menu-user__submenu login-box login-box--right">
  <ul class="login-box__content">
    <% if current_collective.try(:persisted?) %>
      <li class="menu-user__submenu__item">
        <%= link_to 'Adicionar evento',
          new_collective_intervention_path(collective_id: current_collective),
          class: 'menu-user__submenu__link' %>
      </li>

      <li class="menu-user__submenu__item">
        <%= link_to 'Ver praça',
          collective_path(current_collective),
          class: 'menu-user__submenu__link' %>
      </li>

      <li class="menu-user__submenu__item">
        <%= link_to 'Editar praça',
          edit_collective_path(current_collective),
          class: 'menu-user__submenu__link' %>
      </li>
    <% else %>
      <li class="menu-user__submenu__item">
        <%= link_to 'Criar praça',
          new_collective_path,
          class: 'menu-user__submenu__link' %>
      </li>
    <% end %>

    <li class="menu-user__submenu__item">
      <%= link_to I18n.t("layouts.application.sign_out"),
                  sign_out_path,
                  method: :delete,
                  class: 'menu-user__submenu__link' %>
    </li>
  </ul>
</div>