config/routes.rb
Rails.application.routes.draw do
  get '/sobre' => 'pages#about'
  get '/termos-de-uso' => 'pages#terms', as: 'termos'
  get '/batata-precisa-de-voce' => 'pages#batata-precisa-de-voce'
  get '/baixo-centro' => 'pages#baixo-centro'
  get '/boa-praca' => 'pages#boa-praca'

  get '/search', to: 'home#search'
  get '/auth/:provider/callback' => 'omniauth#create'

  resources :users,
    :controller => 'users',
    :only => [:new, :create, :destroy]

  root to: 'home#index'

  localized do
    resources :interventions, only: [:index]
    resources :collectives, only: [:create, :index, :show, :edit, :update, :new] do
      resources :interventions, module: 'collectives'
    end
  end
end

app/models/collective.rb
class Collective < ActiveRecord::Base
  include Taggable
  include PgSearch
  extend FriendlyId

  belongs_to :user
  has_many :interventions, dependent: :delete_all
  has_many :taggable_tags, as: :taggable
  has_many :tags, through: :taggable_tags

  validates_presence_of :name
  validates_presence_of :avatar
  validates_presence_of :cover
  validates_presence_of :about
  validates_presence_of :email
  validates :website, :url => { allow_nil: true, allow_blank: true }
  validates_email_format_of :email

  attachment :avatar
  attachment :cover

  multisearchable against: [:name, :about]
  pg_search_scope :search,
    against: [:name, :about],
    using: [:tsearch, :trigram, :dmetaphone],
    ignoring: :accents

  paginates_per 12

  friendly_id :name, use: [:slugged, :finders]

  def to_param
    self.slug
  end
end

app/models/intervention.rb
class Intervention < ActiveRecord::Base
  include PgSearch
  include Taggable
  extend FriendlyId

  belongs_to :collective
  has_one :user, through: :collective
  has_many :taggable_tags, as: :taggable
  has_many :tags, through: :taggable_tags

  validates :name, :description, :schedule, :avatar, :cover, :place, presence: true

  validates :event_link, :url => { allow_nil: true, allow_blank: true }
  validates_presence_of :collective

  attachment :avatar
  attachment :cover

  friendly_id :name, use: [:slugged, :finders]

  multisearchable against: [:name, :description]
  pg_search_scope :search,
    against: [:name, :description],
    using: [:tsearch, :trigram, :dmetaphone],
    ignoring: :accents

  paginates_per 12

  scope :upcoming, -> { where('schedule > ?', Time.current) }

  def to_param
    self.slug
  end
end

app/controllers/collectives/interventions_controller.rb
class Collectives::InterventionsController < ApplicationController
  before_action :require_login, only: [:new, :edit, :update, :create, :destroy]
  before_action :find_intervention, only: [:show, :edit, :update, :destroy]
  before_action :find_collective, only: [:new, :index, :edit, :update, :create, :destroy]

  def new
    @tags = Tag.all
    authorize @collective, :create_intervention?
    @intervention = Intervention.new(collective: collective)
  end

  def index
    @tags = Tag.all
    @interventions = find_collective_interventions
  end

  def show
  end

  def edit
    @tags = Tag.all
    authorize @intervention, :edit?
  end

  def update
    authorize @intervention, :edit?
    @tags = Tag.all
    if @intervention.update(intervention_params)
      redirect_to [@collective, @intervention]
    else
      render 'edit'
    end
  end

  def create
    authorize @collective, :create_intervention?
    @tags = Tag.all
    @intervention = collective.interventions
      .create(intervention_params)
    if @intervention.persisted?
      redirect_to [@collective, @intervention]
    else
      render 'new'
    end
  end

  def destroy
    authorize @intervention, :edit?
    @intervention.destroy
    redirect_to @intervention.collective
  end

  private

  def intervention_params
    params.require(:intervention).permit(:name, :description,
                                         :place, :schedule, :event_link,
                                         :avatar, :cover,
                                         tag_ids: [])
  end

  def find_intervention
    @intervention = Intervention.friendly.find(params[:id])
  end

  def find_collective
    @collective = collective
  end

  def find_collective_interventions
    interventions = collective.interventions
    Seeker.new(params, interventions).find_interventions
      .page(params[:page]).per(params[:per_page])
  end

  def collective
    Collective.find(params[:collective_id])
  end
end

app/controllers/collectives_controller.rb
class CollectivesController < ApplicationController
  before_action :set_tags, only: [:new, :edit, :update, :create]
  before_action :set_collective, only: [:edit, :create, :update]
  before_action :require_login, only: [:new, :edit, :create, :update]

  def index
    @tags = Tag.all
    @collectives = find_collectives
    og_metas
  end

  def new
    if current_user.collective
      return redirect_to action: :edit, id: current_user.collective.id
    end
    collective_name = params[:collective] ? params[:collective][:name] : ''
    @collective = current_user.build_collective(name: collective_name)
  end

  def show
    @collective = Collective.friendly.find(params[:id])

    og_metas title:        @collective.name,
             description:  @collective.about,
             image:        request.base_url + Refile.attachment_url(@collective, :avatar)
  end

  def edit
    authorize @collective, :edit?
  end

  def create
    if @collective.save
      redirect_to @collective, notice: 'Cadastrado com sucesso!'
    else
      render action: "new"
    end
  end

  def update
    authorize @collective, :edit?

    if @collective.update(collective_params)
      redirect_to @collective, notice: 'Atualizado com sucesso.'
    else
      render action: "edit"
    end
  end

  private

  def set_tags
    @tags = Tag.all
  end

  def find_collectives
    Seeker.new(params).find_collectives
      .page(params[:page]).per(params[:per_page])
  end

  def set_collective
    @collective = current_user.collective ||
      current_user.build_collective(collective_params)
  end

  def collective_params
    params.require(:collective)
      .permit(:name, :address , :email, :phone, :about,
              :facebook_link, :responsible, :avatar, :cover,
              :website,
              tag_ids: [])
  end
end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
  def index
    params[:view] ||= 'map'
    @tags = Tag.with_collectives
    @interventions = find_interventions

    og_metas
  end

  private

  def find_interventions
    interventions = Seeker.new(params).find_interventions
      .upcoming
      .page(params[:page]).per(params[:per_page])
  end
end

app/views/collectives/interventions/_details.html.erb
<div class="collective-main__item">
  <div class="collective">
    <div class="wrapper">
      <header class="collective__header">
        <%= link_to collective_intervention_path(intervention.collective, intervention) do %>
          <h3 class="collective__title"><%= intervention.name %></h3>
        <% end %>
        <ul class="list-info--small">
          <%= content_tag :li,
            intervention.place,
            class: 'list-info__item list-info__item--icon-pin' if intervention.place %>

          <%= content_tag :li,
            intervention.schedule.to_s(:long),
            class: 'list-info__item list-info__item--icon-date' if intervention.schedule %>
        </ul>

        <ul class="list-tags list-tags--small">
          <% intervention.tags.each do |tag| %>
          <li class="list-tags__item list-tags--icon-<%= tag[:name].parameterize %>" data-tooltip="<%= tag[:name] %>">
            <a class="list-tags__link" href="javascript:;"><%= tag[:name] %></a>
          </li>
          <% end %>
        </ul>
      </header>

      <%= link_to collective_path(intervention.collective) do %>
        <div class="intervention-collective">
          <%= image_tag attachment_url(intervention.collective, :avatar, :fill, 128, 128), class: "intervention-collective__image" %>
          <div class="intervention-collective__name"><%= intervention.collective.name %></div>
        </div>
      <% end %>
    </div>

    <%= link_to collective_intervention_path(intervention.collective, intervention) do %>
      <figure class="collective__image"
        data-cover="<%= attachment_url(intervention, :cover, :fit, 400, 200) %>">
      </figure>
    <% end %>
  </div>
</div>

app/views/collectives/interventions/_form.html.erb
<%= simple_form_for([@collective, @intervention]) do |f| %>
  <% if @intervention.errors.any? %>
    <div class="flash error">
      <ul>
      <% @intervention.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-default__row">
    <div class="form-default__column form-default__column--two-columns">
      <div class="form-default__row">
        <%= f.input :name, wrapper: false %>
      </div>

      <div class="form-default__row">
        <div class="form-default__column--two-columns">
          <%= f.input :place, wrapper: false %>
        </div>

        <div class="form-default__column--two-columns">
          <%= f.input :event_link, wrapper: false %>
        </div>
      </div>

      <div class="form-default__row form-default--margin-bottom-none">
        <%= f.input :schedule, wrapper: false %>
      </div>
    </div>

    <div class="form-default__column form-default__column--two-columns">
      <%= f.input :description, as: :text, wrapper: false, input_html: { class: 'textarea-about' } %>
    </div>
  </div>

  <div class="form-default__row">
    <div class="form-default__column--two-columns">
      <div class="form-default__column--two-columns">
        <%= f.label :avatar %> <%= f.attachment_field :avatar %>
        <% if @intervention.persisted? && @intervention.avatar %>
          <%= image_tag attachment_url(@intervention, :avatar, :fit, 200, 200) %>
        <% end %>
      </div>

      <div class="form-default__column--two-columns">
        <%= f.label :cover %> <%= f.attachment_field :cover %>
        <% if @intervention.persisted? && @intervention.cover %>
          <%= image_tag attachment_url(@intervention, :cover, :fit, 200, 200) %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="form-default__row">
    <h3 class="form-default--subtitle">Interesses</h3>

    <div class="form-list-tags">
      <%= f.collection_check_boxes :tag_ids, @tags, :id, :name, item_wrapper_class: 'form-list-tags__item' %>
    </div>
  </div>

  <div class="form-default__row form-default--text-right">
    <%= f.submit %>
  </div>
<% end %>

app/views/collectives/interventions/edit.html.erb
<div class="form-default wrapper">
  <h2 class="form-default__title"><%= t(".title") %></h2>
  <%= render 'form' %>
</div>

app/views/collectives/interventions/index.html.erb
<section class="cover-pages cover-pages--shadow cover-pages--shadow--up">
  <div class="cover-pages__form">
    <%= render partial: 'interventions/search' -%>
  </div>

  <figure class="cover-pages__image" data-cover="<%= rand_cover %>"></figure>
</section>

<nav class="navigation-collectives">
  <div class="wrapper">
    <div class="navigation-collectives__left">
      <%= link_to I18n.t("interventions.new.title").pluralize, interventions_path(search_params), class: 'navigation-collectives__link navigation-collectives__link--current' %>
      <%= link_to I18n.t("collectives.show.title").pluralize, collectives_path(search_params), class: 'navigation-collectives__link' %>
    </div>

    <div class="navigation-collectives__right">
      <%= link_to 'Lista', interventions_path(search_params.merge(view: 'list')), class: 'navigation-collectives__link' %>

      <%= link_to 'Mapa', interventions_path(search_params.merge(view: 'map')), class: 'navigation-collectives__link' %>
    </div>
  </div>
</nav>

<section class="collective-main">
  <div class="wrapper">
  <div class="collective-main__list">
      <% @interventions.each do |intervention| %>
        <%= render 'collectives/interventions/details', intervention: intervention %>
      <% end %>
    </div>

    <div class="collective-main__pagination">
      <%= paginate @interventions %>
    </div>
  </div>
</section>

app/views/collectives/interventions/new.html.erb
<div class="form-default wrapper">
  <h2 class="form-default__title"><%= t(".title") %></h2>

  <%= render 'form' %>
</div>

app/views/collectives/interventions/show.html.erb
<section class="cover-pages cover-pages--shadow cover-pages--shadow--up">
  <div class="wrapper">
    <h2 class="cover-pages__title-page"><%= @intervention.name %></h2>
  </div>

  <figure class="cover-pages__image"
    data-cover="<%= attachment_url(@intervention, :cover) %>">
  </figure>
</section>

<main class="main wrapper">
  <aside class="sidebar">
    <figure class="sidebar__image"
      data-cover="<%= attachment_url(@intervention, :avatar, :fill, 200, 200) %>">
    </figure>

    <% if policy(@intervention).edit? %>
      <nav class="menu-user-action">
        <%= link_to 'Editar', edit_collective_intervention_path(@intervention.collective, @intervention), class: "button button-half" %>
        <%= link_to 'Excluir', collective_intervention_path(@intervention.collective, @intervention), method: :delete, class: "button button-half" %>
      </nav>
    <% end %>

    <ul class="list-tags list-tags--large">
      <% @intervention.tags.each do |tag| %>
        <li class="list-tags__item list-tags--icon-<%= tag[:name].parameterize %>" data-tooltip="<%= tag[:name] %>">
          <a class="list-tags__link" href="javascript:;"><%= tag[:name] %></a>
        </li>
      <% end %>
    </ul>

    <ul class="list-info">
      <%= content_tag :li,
        @intervention.place,
        class: 'list-info__item list-info__item--icon-pin' if @intervention.place %>

      <%= content_tag :li,
        @intervention.schedule.to_s(:long),
        class: 'list-info__item list-info__item--icon-date' if @intervention.schedule %>

      <%= content_tag :li,
        link_to(@intervention.event_link, @intervention.event_link),
        class: 'list-info__item list-info__item--icon-notebook' if @intervention.event_link %>
    </ul>

    <div class="fb-like" data-width="230" data-href="<%= request.url %>" data-show-faces="true" data-share="true"></div>
  </aside>

  <div class="content">
    <article class="text">
      <%= simple_format(@intervention.description) %>
    </article>

    <div class="fb-comments" data-href="<%= request.url %>" data-width="100%" data-numposts="10"></div>
  </div>
</main>